name: Code coverage

on:
  workflow_dispatch: {}
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  codecov:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup spack
      uses: spack/setup-spack@v2
      with:
        ref: develop
        color: true
        path: spack

    - name: Add mochi-spack-packages
      run: |
        git clone https://github.com/mochi-hpc/mochi-spack-packages
        spack -e tests repo add mochi-spack-packages

    - name: Install spack environment
      run: |
        spack -e tests install

    - name: Show spack-installed packages for debugging
      run: |
        spack -e tests find -dlv

    - name: Build code and run unit tests
      run: |
        eval `spack env activate --sh tests`
        mkdir build
        cd build
        cmake .. -DENABLE_COVERAGE=ON \
                 -DENABLE_TESTS=ON \
                 -DCMAKE_BUILD_TYPE=Debug \
                 -DENABLE_LEVELDB=ON \
                 -DENABLE_ROCKSDB=ON \
                 -DENABLE_BERKELEYDB=ON \
                 -DENABLE_TKRZW=ON \
                 -DENABLE_GDBM=ON \
                 -DENABLE_LMDB=ON \
                 -DENABLE_UNQLITE=ON \
                 -DENABLE_LUA=ON \
                 -DENABLE_REMI=ON \
                 -DENABLE_PYTHON=ON
        make
        make test

    - name: Send coverage report
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
        verbose: true
        gcov: true
