name: codecov

on:
  workflow_dispatch: {}
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Add latest Spack release
      run: |
        git clone https://github.com/spack/spack.git /opt/spack
    - name: Find external packages
      run: |
        eval `/opt/spack/bin/spack env activate --sh .` &&
        /opt/spack/bin/spack external find --not-buildable cmake &&
        /opt/spack/bin/spack external find --not-buildable perl
    - name: Add mochi-spack-packages
      run: |
        git clone https://github.com/mochi-hpc/mochi-spack-packages /opt/spack/mochi-spack-packages
        /opt/spack/bin/spack repo add /opt/spack/mochi-spack-packages
    - name: Install Package from Spack
      run: |
        eval `/opt/spack/bin/spack env activate --sh .` &&
        /opt/spack/bin/spack install --fail-fast
    - name: Show Spack installed packages for debugging
      run: |
        eval `/opt/spack/bin/spack env activate --sh .` &&
        /opt/spack/bin/spack find -dlv
    - name: Run test
      run: |
        eval `/opt/spack/bin/spack env activate --sh .` &&
        mkdir build && cd build &&
        cmake .. -DENABLE_COVERAGE=ON -DENABLE_TESTS=ON -DCMAKE_BUILD_TYPE=Debug -DENABLE_LEVELDB=ON -DENABLE_ROCKSDB=ON -DENABLE_BERKELEYDB=ON -DENABLE_TKRZW=ON -DENABLE_GDBM=ON -DENABLE_LMDB=ON -DENABLE_UNQLITE=ON -DENABLE_LUA=ON &&
        make && make test
    - name: Upload code coverage files
      run: |
        bash <(curl -s https://codecov.io/bash)
