name: Unit tests

on:
  workflow_dispatch: {}
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Setup spack
      uses: spack/setup-spack@v2
      with:
        ref: develop
        color: true
        path: spack

    - name: Install mpich
      run: |
        sudo apt install -y libmpich-dev

    - name: Find external packages
      run: |
        spack -e tests external find --not-buildable cmake
        spack -e tests external find --not-buildable perl
        spack -e tests external find --not-buildable python
        spack -e tests external find --not-buildable mpich
        spack -e tests external find --not-buildable m4
        spack -e tests external find --not-buildable libtool
        spack -e tests external find --not-buildable autoconf
        spack -e tests external find --not-buildable automake
        spack -e tests external find --not-buildable pkg-config
        spack -e tests external find --not-buildable gmake

    - name: Add mochi-spack-packages
      run: |
        git clone https://github.com/mochi-hpc/mochi-spack-packages
        spack -e tests repo add mochi-spack-packages

    - name: Concretizing spack environment
      run: |
        spack -e tests concretize -f

    - name: Create cache key from environment file
      run: |
        jq --sort-keys 'del(.spack.commit) | del(.roots)' tests/spack.lock > key.json

    - name: Restore Spack cache
      uses: actions/cache@v2
      with:
        path: ~/.spack-ci
        key: spack-${{ hashFiles('key.json') }}

    - name: Installing spack environment
      run: |
        spack -e tests install

    - name: Show spack-installed packages for debugging
      run: |
        spack -e tests find -dlv

    - name: Build code and run unit tests
      run: |
        eval `spack env activate --sh tests`
        mkdir build
        cd build
        cmake .. -DENABLE_TESTS=ON \
                 -DCMAKE_BUILD_TYPE=Debug \
                 -DENABLE_LEVELDB=ON \
                 -DENABLE_ROCKSDB=ON \
                 -DENABLE_BERKELEYDB=ON \
                 -DENABLE_TKRZW=ON \
                 -DENABLE_GDBM=ON \
                 -DENABLE_LMDB=ON \
                 -DENABLE_UNQLITE=ON \
                 -DENABLE_LUA=ON \
                 -DENABLE_PYTHON=ON \
                 -DENABLE_REMI=ON \
                 -DENABLE_YCSB=ON
        make
        ctest --output-on-failure
